name: iar

on:
  pull_request:
    paths:
      - '.github/workflows/iar_test.yml'
      - '!**/*.md'
  workflow_dispatch:

# Ensure only one instance of the workflow is running at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@f608f32a6d83e90d79e1f2bbb7812fdb94bf1679 # v1
        with:
          config: "./test/vcpkg-configuration.json"
          vcpkg-downloads: "${{ github.workspace }}/.vcpkg/downloads"
          cache: "-"

      - name: Activate Arm tool license
        working-directory: ./test
        run: |
          armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0

      - name: Binary version info
        shell: bash
        run: |
          csolution -V
          cpackget -V
          cbuild -V
          cbuild2cmake -V
          cbuildgen -V

      - name: Build Example
        shell: bash
        run: |
          export IAR_LMS_BEARER_TOKEN=${{ secrets.IAR_TOKEN }}
          csolution list toolchains
          cbuild ./test/data/build-c/solution.csolution.yml -p --update-rte
