name: iar

on:
  pull_request:
    paths:
      - '.github/workflows/iar_test.yml'
      - '!**/*.md'
  workflow_dispatch:

# Ensure only one instance of the workflow is running at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download IAR artifacts
        shell: bash
        run: |
          curl -L https://github.com/iarsystems/arm/releases/download/9.60.4/cxarm-9.60.4-linux-x86_64-minimal.tar.bz2 --output ./cxarm-9.60.4-linux-x86_64-minimal.tar.bz2
          curl -L https://github.com/iarsystems/arm/releases/download/9.60.4/cxarm-9.60.4-linux-x86_64-minimal.tar.bz2.sha256 --output ./cxarm-9.60.4-linux-x86_64-minimal.tar.bz2.sha256

      - name: Validate the hash
        shell: bash
        run: sha256sum --check cxarm-9.60.4-linux-x86_64-minimal.tar.bz2.sha256

      - name: Extract IAR artifacts
        shell: bash
        run: tar -xvf cxarm-9.60.4-linux-x86_64-minimal.tar.bz2

      - name: Setup vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@f608f32a6d83e90d79e1f2bbb7812fdb94bf1679 # v1
        with:
          config: "./test/vcpkg-configuration.json"
          vcpkg-downloads: "${{ github.workspace }}/.vcpkg/downloads"
          cache: "-"

      - name: Activate Arm tool license
        run: |
          armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
        working-directory: ./test

      - name: Binary version info
        shell: bash
        run: |
          csolution -V
          cpackget -V
          cbuild -V
          cbuild2cmake -V
          cbuildgen -V

      - name: List registered toolchains
        shell: bash
        run: |
          export IAR_TOOLCHAIN_9_60_4=$(pwd)/cxarm-9.60.4/arm/bin
          export IAR_LMS_BEARER_TOKEN=${{ secrets.IAR_TOKEN }}
          csolution list toolchains

      - name: Build Example
        shell: bash
        run: |
          export IAR_TOOLCHAIN_9_60_4=$(pwd)/cxarm-9.60.4/arm/bin
          export IAR_LMS_BEARER_TOKEN=${{ secrets.IAR_TOKEN }}
          cbuild ./test/data/build-c/solution.csolution.yml -p --update-rte
