name: performance test

on:
  pull_request:
    paths:
      - '.github/workflows/perf_record.yml'
      - '.github/matrix_includes.json'
      - 'test/**'
      - '!test/performance_test.py'
      - '!**/*.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: JoshuaTheMiller/conditional-build-matrix@81b51eb8d89e07b86404934b5fecde1cea1163a5 # v2.0.1        
        id: set-matrix
        with:
          inputFile: '.github/matrix_includes.json'
          filter: '[?runOnBranch==`always`]'

  test:
    needs: [ matrix_prep ]
    runs-on: ${{ matrix.runs_on }}
    continue-on-error: true
    strategy:
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pip dependencies
        run: |
            pip install --upgrade pip
            pip install -r test/requirements.txt

      - name: Setup vcpkg environment
        uses: ARM-software/cmsis-actions/vcpkg@f608f32a6d83e90d79e1f2bbb7812fdb94bf1679 # v1
        with:
          config: "./test/vcpkg-configuration.json"
          vcpkg-downloads: "${{ github.workspace }}/.vcpkg/downloads"
          cache: "-"

      - name: Activate Arm tool license
        run: |
          armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
        working-directory: ./test

      - name: Binary version info
        shell: bash
        run: |
          csolution${{ matrix.binary_extension }} -V
          cpackget${{ matrix.binary_extension }} -V
          cbuild${{ matrix.binary_extension }} -V
          cbuild2cmake${{ matrix.binary_extension }} -V
          cbuildgen${{ matrix.binary_extension }} -V

      - name: Run Test
        shell: bash
        continue-on-error: true
        working-directory: ./test
        run: |
          python ./performance_test.py -i $(pwd)/data

      - name: Print Perf Report
        if: always()
        run: |
          echo "![Image](./execution_times_plot.png)" >> "$GITHUB_STEP_SUMMARY"

      - name: Archieve test results
        if: always()
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: perf_reports-${{ matrix.target }}-${{ matrix.arch }}
          path: 
